### ISSUE TITLE
JdbcWriter output datatypes should be customizable

### ISSUE THREAD

**Issue by vlkong** [IBMDecisionOptimization/OPL-jdbc-custom-data-source#3]
The default behaviour today for instance is to use SQL type FLOAT for OPL FLOATs. Howerver, precision on FLOAT depend on database, and one may want to customize that type anyway.

We should be able to customize it without editing the code and recompiling.

**Comment by djunglas** [comment]
I think we should do things in a completely different way. At the moment, the JdbcWriter explicilty
- drops the table
- recreates the table from scratch
- fills the new table
That makes a lot of assumptions about the database layout and adds some unnecessary limitations. Suppose for example you don't want to create a new table for the results but want to update an existing table (for example, in a table of employees you want to fill the "working days" column). That is not possible. To fix that I think we should extend the syntax for writing. Instead of
`addWriteMapping("Result", "result");`
the user should be able to say
`addWriteMapping("Result", "UPDATE result WITH (?, ?, ?) WHERE name=?")`
That is, the user can provide a full SQL statement that tells how to update. Parameters are filled from left to right (or we can allow some magic). That gives maximum flexibility.
Of course, we would then also have to provide a way that a user can drop/create tables in case they don't exist.

If we implement all of the above then we don't have to worry about the types. The user will pick the correct types in the SQL statement and we only have to use setLong(), setDouble() and setString() in the JDBC API (depending on the type of the tuple field).

**Comment by vlkong** [comment]
How about this: instead of just allowing for some output mapping, we allow to customize more parameters for the output.

We can add a method to set the parameters for the output:

```
addOutputParameters(String oplTable,
   boolean dropTable,
   String createStatement,
   String updateStatement)
```

`addWriteMapping(table, statement)` will have the same behaviour than currently and will just call: `addOutputParameters(table, true, null, null)` (the nulls for createStatement and updateStatement means use default ones)

We currently use only PreparedStatements. Maybe it's worth adding the possibility to use NamedPreparedStatements `UPDATE result with (:x, :y, :z) WHERE name=:name` (we would map the OPL tuple fields or just :value for scalar). This will  address your use case where one wants to update a row instead of just inserting.

**Comment by djunglas** [comment]
Using names prepared statements sounds like a very good idea. But I think we should also support "regular" prepared statements: if a user wants to write an array or a singleton value he probably does not want to use a named statement. Also using names will incurr slightly more overhead when writing a large number of elements.

For the other things: what you suggest will work. However, I'm afraid that whatever we do, there will be a usecase that we don't cover. So the most flexible thing would be to just provide a way that allows executing _any_ SQL statement. In the old days we had the [DBExecute](https://www.ibm.com/support/knowledgecenter/en/SSSA5P_12.6.3/ilog.odms.ide.help/OPL_Studio/opllang_quickref/topics/tlr_opl_db_DBExecute.html) function for this.

**Comment by vlkong** [comment]
Yes sure, we can support both anonymous and named prepared statements.

As for a DBExecute equivalent, I see nothing that prevents us from providing an equivalent. I'll go ahead and add that too.

**Comment by vlkong** [comment]
Sample https://github.com/IBMDecisionOptimization/OPL-jdbc-custom-data-source/tree/master/examples/studio_integration adresses the issues around creating/updating databases
Named parameter prepared statements are not yet implemented, should be shortly.

```
	// create result table
	db.execute("DROP TABLE result");
  	db.execute("CREATE TABLE result(oil VARCHAR(30), gas VARCHAR(30), blend FLOAT, a FLOAT)");
  	
    // write results to database
  	db.update("items", "INSERT INTO result(oil, gas, blend, a) VALUES (?,?,?,?)");
```

**Comment by vlkong** [comment]
https://github.com/IBMDecisionOptimization/OPL-jdbc-custom-data-source/pull/17 adresses named parameter prepared statements. One can now write something like:

```
db.update("items", "INSERT INTO result(oil, gas, blend, a) VALUES (:oil, :gas, :blend, :a))
```
